# Generated by Django 5.0.6 on 2025-09-29 06:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=50, unique=True, verbose_name='Employee Code')),
                ('name', models.CharField(max_length=255, verbose_name='Full Name')),
                ('location', models.CharField(max_length=100, verbose_name='Location')),
                ('role', models.CharField(choices=[('User', 'User'), ('Admin', 'Admin'), ('Supervisor', 'Supervisor')], default='User', max_length=20, verbose_name='Role')),
                ('card_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='Card Number')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'biometric_employees',
                'indexes': [models.Index(fields=['employee_code'], name='biometric_e_employe_d8128d_idx'), models.Index(fields=['location'], name='biometric_e_locatio_2475c8_idx')],
            },
        ),
        migrations.CreateModel(
            name='PunchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('punch_time', models.DateTimeField(verbose_name='Punch Time')),
                ('device_name', models.CharField(max_length=100, verbose_name='Device Name')),
                ('direction', models.CharField(choices=[('IN', 'Check In'), ('OUT', 'Check Out')], max_length=3, verbose_name='Direction')),
                ('raw_data', models.JSONField(default=dict, verbose_name='Raw Data')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='punch_logs', to='biometric.employee')),
            ],
            options={
                'verbose_name': 'Punch Log',
                'verbose_name_plural': 'Punch Logs',
                'db_table': 'biometric_punch_logs',
                'ordering': ['-punch_time'],
                'indexes': [models.Index(fields=['punch_time'], name='biometric_p_punch_t_b04199_idx'), models.Index(fields=['employee', 'punch_time'], name='biometric_p_employe_6d30c0_idx'), models.Index(fields=['device_name'], name='biometric_p_device__f88c5f_idx')],
            },
        ),
    ]
